export const permissions = {
  accountGroupsView: "finance.accounts.view",
  accountGroupsCreate: "finance.accounts.create",
  accountsView: "finance.accounts.view",
  accountsCreate: "finance.accounts.create",
  accountsUpdate: "finance.accounts.update",
  accountsDelete: "finance.accounts.delete",
  fiscalYearsView: "finance.fiscal_years.view",
  fiscalYearsCreate: "finance.fiscal_years.create",
  fiscalYearsUpdate: "finance.fiscal_years.update",
  fiscalYearsClose: "finance.fiscal_years.close",
  journalEntriesView: "finance.journal_entries.view",
  journalEntriesCreate: "finance.journal_entries.create",
  journalEntriesUpdate: "finance.journal_entries.update",
  journalEntriesDelete: "finance.journal_entries.delete",
  journalEntriesPost: "finance.journal_entries.post",
  journalEntriesCancel: "finance.journal_entries.cancel",
  trialBalanceView: "finance.reports.trial_balance.view",
  accountingSettingsView: "finance.accounting_settings.view",
  accountingSettingsUpdate: "finance.accounting_settings.update",
} as const;
