import Link from "next/link";
import { ModuleHeader } from "../../../../components/layout/ModuleHeader";
import { listAccounts } from "../../../../features/finance/accounting/api";
import { createReceiptFromInvoiceAction } from "../../../../features/finance/customer-receipts/actions";
import { getSalesInvoiceReceipts } from "../../../../features/finance/customer-receipts/api";
import { createCreditNoteFromInvoiceAction } from "../../../../features/sales/credit-notes/actions";
import { getSalesInvoiceCreditNotes } from "../../../../features/sales/credit-notes/api";
import { getSalesInvoiceCreditAllocations } from "../../../../features/sales/credit-note-allocations/api";
import { createDebitNoteFromInvoiceAction } from "../../../../features/sales/debit-notes/actions";
import { getSalesInvoiceDebitNotes } from "../../../../features/sales/debit-notes/api";
import { cancelSalesInvoiceAction, issueSalesInvoiceAction, postSalesInvoiceAccountingAction } from "../../../../features/sales/invoices/actions";
import { getSalesInvoice } from "../../../../features/sales/invoices/api";

export default async function InvoiceDetailPage({ params }: { params: { id: string } }) {
  const [invoice, receipts, creditNotes, creditAllocations, debitNotes, accounts] = await Promise.all([getSalesInvoice(params.id), getSalesInvoiceReceipts(params.id), getSalesInvoiceCreditNotes(params.id), getSalesInvoiceCreditAllocations(params.id), getSalesInvoiceDebitNotes(params.id), listAccounts({ isActive: "true", pageSize: "100" })]);
  const depositAccounts = accounts.rows.filter((account) => account.isActive && (account.isCashAccount || account.isBankAccount));
  return (
    <main className="page-shell">
      <ModuleHeader title={invoice.invoiceNumber} eyebrow="Sales Invoices" description={`Customer invoice for ${invoice.customerId}`} actions={<>{invoice.status === "DRAFT" ? <Link className="vercent-button" href={`/sales/invoices/${invoice.id}/edit`}>Edit</Link> : null}<Link className="vercent-button secondary" href="/sales/invoices">Back</Link></>} />
      <section className="grid-panel">
        <article className="metric-card"><span>Status</span><strong>{invoice.status}</strong></article><article className="metric-card"><span>Payment</span><strong>{invoice.paymentStatus}</strong></article><article className="metric-card"><span>Total</span><strong>{invoice.currency} {invoice.totalAmount.toLocaleString("en-IN")}</strong></article><article className="metric-card"><span>Amount due</span><strong>{invoice.amountDue.toLocaleString("en-IN")}</strong></article>
        <article className="metric-card"><span>Amount paid</span><strong>{invoice.amountPaid.toLocaleString("en-IN")}</strong></article><article className="metric-card"><span>Credited</span><strong>{invoice.creditedAmount.toLocaleString("en-IN")}</strong></article><article className="metric-card"><span>Debited</span><strong>{invoice.debitedAmount.toLocaleString("en-IN")}</strong></article><article className="metric-card"><span>Net due</span><strong>{invoice.amountDue.toLocaleString("en-IN")}</strong></article>
        <article className="metric-card"><span>Sales order</span><strong>{invoice.salesOrderId ? <Link href={`/sales/orders/${invoice.salesOrderId}`}>{invoice.salesOrderId}</Link> : "-"}</strong></article><article className="metric-card"><span>Delivery note</span><strong>{invoice.deliveryNoteId ? <Link href={`/sales/delivery-notes/${invoice.deliveryNoteId}`}>{invoice.deliveryNoteId}</Link> : "-"}</strong></article>
      </section>
      <section className="vercent-table-wrap"><table className="vercent-table"><thead><tr><th>#</th><th>Item</th><th>Qty</th><th>Unit</th><th>Discount</th><th>Taxable</th><th>Tax</th><th>Total</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.id}><td>{line.lineNumber}</td><td>{line.itemName}<span>{line.itemId}</span></td><td>{line.quantity}</td><td>{line.unitPrice.toLocaleString("en-IN")}</td><td>{line.discountAmount.toLocaleString("en-IN")}</td><td>{line.taxableAmount.toLocaleString("en-IN")}</td><td>{line.taxAmount.toLocaleString("en-IN")}</td><td>{line.lineTotal.toLocaleString("en-IN")}</td></tr>)}</tbody></table></section>
      <section className="grid-panel"><article className="metric-card"><span>Subtotal</span><strong>{invoice.subtotalAmount.toLocaleString("en-IN")}</strong></article><article className="metric-card"><span>Discount</span><strong>{invoice.discountAmount.toLocaleString("en-IN")}</strong></article><article className="metric-card"><span>Taxable</span><strong>{invoice.taxableAmount.toLocaleString("en-IN")}</strong></article><article className="metric-card"><span>Tax</span><strong>{invoice.taxAmount.toLocaleString("en-IN")}</strong></article></section>
      {invoice.status === "DRAFT" ? <section className="vercent-panel"><h2>Actions</h2><form action={issueSalesInvoiceAction.bind(null, invoice.id)} className="vercent-toolbar"><input name="invoiceDate" type="date" defaultValue={invoice.invoiceDate} /><button type="submit">Issue invoice</button></form><form action={cancelSalesInvoiceAction.bind(null, invoice.id)}><button type="submit">Cancel draft</button></form></section> : null}
      <section className="vercent-panel"><h2>Accounting</h2><p>Status: <strong>{invoice.accountingStatus}</strong>{invoice.journalEntryId ? <> - Journal: <Link href={`/finance/journal-entries/${invoice.journalEntryId}`}>{invoice.journalEntryId}</Link></> : null}</p>{invoice.status === "ISSUED" && invoice.accountingStatus === "NOT_POSTED" ? <form action={postSalesInvoiceAccountingAction.bind(null, invoice.id)} className="vercent-toolbar"><input name="postingDate" type="date" defaultValue={invoice.invoiceDate} /><button type="submit">Post to Accounting</button><Link href="/finance/accounting/settings">Configure settings</Link></form> : null}<p>GST e-invoice integration and e-way bill integration are not implemented yet.</p></section>
      <section className="vercent-panel"><h2>Receipts</h2><p>Amount paid: <strong>{invoice.amountPaid.toLocaleString("en-IN")}</strong> | Amount due: <strong>{invoice.amountDue.toLocaleString("en-IN")}</strong> | Payment status: <strong>{invoice.paymentStatus}</strong></p>{receipts.length ? <table className="vercent-table"><thead><tr><th>Receipt</th><th>Status</th><th>Method</th><th>Amount</th></tr></thead><tbody>{receipts.map((receipt) => <tr key={receipt.id}><td><Link href={`/finance/customer-receipts/${receipt.id}`}>{receipt.receiptNumber}</Link></td><td>{receipt.status}</td><td>{receipt.paymentMethod}</td><td>{receipt.amountReceived.toLocaleString("en-IN")}</td></tr>)}</tbody></table> : <p>No receipts recorded yet.</p>}{invoice.status === "ISSUED" && invoice.accountingStatus === "POSTED" && invoice.amountDue > 0 ? <form action={createReceiptFromInvoiceAction.bind(null, invoice.id)} className="vercent-toolbar"><input name="amountReceived" type="number" step="0.01" defaultValue={invoice.amountDue} /><select name="paymentMethod" defaultValue="BANK_TRANSFER"><option>CASH</option><option>BANK_TRANSFER</option><option>CHEQUE</option><option>UPI</option><option>CARD</option><option>OTHER</option></select><select name="depositAccountId" required>{depositAccounts.map((account) => <option key={account.id} value={account.id}>{account.accountCode} - {account.accountName}</option>)}</select><input name="receiptDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} /><button type="submit">Create Receipt</button></form> : null}</section>
      <section className="vercent-panel"><h2>Credit Notes</h2><p>Credited amount: <strong>{invoice.creditedAmount.toLocaleString("en-IN")}</strong> | Remaining due: <strong>{invoice.amountDue.toLocaleString("en-IN")}</strong></p>{creditNotes.length ? <table className="vercent-table"><thead><tr><th>Credit note</th><th>Status</th><th>Total</th><th>Journal</th></tr></thead><tbody>{creditNotes.map((note) => <tr key={note.id}><td><Link href={`/sales/credit-notes/${note.id}`}>{note.creditNoteNumber}</Link></td><td>{note.status}</td><td>{note.totalAmount.toLocaleString("en-IN")}</td><td>{note.journalEntryId ?? "-"}</td></tr>)}</tbody></table> : <p>No credit notes recorded yet.</p>}{invoice.status === "ISSUED" && invoice.accountingStatus === "POSTED" && invoice.amountDue > 0 ? <form action={createCreditNoteFromInvoiceAction.bind(null, invoice.id)} className="vercent-toolbar"><input name="creditNoteDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} /><input name="reason" placeholder="Reason" /><label><input name="returnToStock" type="checkbox" /> Return stock</label><button type="submit">Create Credit Note</button></form> : null}</section>
      <section className="vercent-panel"><h2>Credit Allocations</h2>{creditAllocations.length ? <table className="vercent-table"><thead><tr><th>Credit note</th><th>Date</th><th>Amount</th><th>Notes</th></tr></thead><tbody>{creditAllocations.map((allocation) => <tr key={allocation.id}><td><Link href={`/sales/credit-notes/${allocation.creditNoteId}`}>{allocation.creditNoteId}</Link></td><td>{allocation.allocationDate}</td><td>{allocation.amount.toLocaleString("en-IN")}</td><td>{allocation.notes ?? "-"}</td></tr>)}</tbody></table> : <p>No explicit credit allocations recorded yet.</p>}</section>
      <section className="vercent-panel"><h2>Debit Notes</h2><p>Debited amount: <strong>{invoice.debitedAmount.toLocaleString("en-IN")}</strong> | Net due: <strong>{invoice.amountDue.toLocaleString("en-IN")}</strong></p>{debitNotes.length ? <table className="vercent-table"><thead><tr><th>Debit note</th><th>Status</th><th>Total</th><th>Journal</th></tr></thead><tbody>{debitNotes.map((note) => <tr key={note.id}><td><Link href={`/sales/debit-notes/${note.id}`}>{note.debitNoteNumber}</Link></td><td>{note.status}</td><td>{note.totalAmount.toLocaleString("en-IN")}</td><td>{note.journalEntryId ?? "-"}</td></tr>)}</tbody></table> : <p>No debit notes recorded yet.</p>}{invoice.status === "ISSUED" && invoice.accountingStatus === "POSTED" ? <form action={createDebitNoteFromInvoiceAction.bind(null, invoice.id)} className="vercent-toolbar"><input name="debitNoteDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} /><input name="reason" placeholder="Reason" /><button type="submit">Create Debit Note</button><Link href="/finance/accounting/settings">Configure debit note accounts</Link></form> : null}</section>
    </main>
  );
}
